// dočasná kontrola: kolik je v seedu jezer a jaké druhy uzlů
const fs = require('fs'), vm = require('vm');
const html = fs.readFileSync('index.html', 'utf8');
const srcs = [...html.matchAll(/src="([^"]+)"/g)].map(m => m[1]).filter(s => s.indexOf('main.js') === -1);
const noop = () => {};
const makeEl = () => ({ addEventListener: noop, classList: { add: noop, remove: noop, toggle: noop, contains: () => false }, style: {}, dataset: {}, children: [], setAttribute: noop, getAttribute: () => null, querySelector: () => null, querySelectorAll: () => [], getContext: () => new Proxy({}, { get: () => noop, set: () => true }), appendChild: noop, innerHTML: '', textContent: '', value: '', scrollTop: 0, width: 800, height: 600, getBoundingClientRect: () => ({ width: 800, height: 600 }) });
const els = {};
const document = { getElementById: id => els[id] || (els[id] = makeEl()), querySelector: () => null, querySelectorAll: () => [], createElement: () => makeEl(), addEventListener: noop, body: makeEl(), documentElement: makeEl(), readyState: 'complete', hidden: false };
const store = {};
const localStorage = { getItem: k => store[k] || null, setItem: (k, v) => { store[k] = String(v); }, removeItem: k => { delete store[k]; } };
const window = { document, localStorage, addEventListener: noop, setTimeout: () => 0, setInterval: () => 0, requestAnimationFrame: () => 0, performance: { now: () => Date.now() }, navigator: { userAgent: 'x' }, devicePixelRatio: 1, innerWidth: 800, innerHeight: 600, location: { search: '' }, matchMedia: () => ({ matches: false, addEventListener: noop }) };
global.window = window; global.document = document; global.localStorage = localStorage; global.requestAnimationFrame = () => 0; global.navigator = window.navigator; global.location = window.location; global.Image = function () {}; global.ResizeObserver = function () {};
for (const s of srcs) vm.runInThisContext(fs.readFileSync(s, 'utf8'), { filename: s });
const G = window.Game;
let to = null; G.showTitleScreen = o => to = o;
vm.runInThisContext(fs.readFileSync('js/main.js', 'utf8'), { filename: 'main.js' });
to.onNewGame('normal');
const lakes = G.WORLD.nodes.filter(n => n.kind === 'lake');
console.log('jezera:', lakes.length, lakes.slice(0, 8).map(n => n.x + ',' + n.y).join(' '));
const kinds = {};
for (const n of G.WORLD.nodes) kinds[n.kind] = (kinds[n.kind] || 0) + 1;
console.log('druhy:', JSON.stringify(kinds));
